version: '3.8'
services:
  fx:
    container_name: fxql-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    # command: "make migrate-dev"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres-db
    image: postgres:latest
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db: